proyecto_BP_CF/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('recetas_compras.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recetas_compras/urls.py
from django.urls import path
from .views.views_semana import Home
from .views.views_ingredientes import ListaIngrediente, CrearIngrediente, DetalleIngrediente, BorrarIngrediente, ActualizarIngrediente
from .views.views_recetas import ListaReceta, DetalleReceta, CrearReceta, BorrarReceta, ActualizarReceta
from .views.views_semana import ListaSemana, DetalleSemana,CrearSemana,CrearSemana2, ActualizarSemana, BorrarSemana

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("lista_ingredientes/", ListaIngrediente.as_view(), name="lista_ingredientes"),
    path("lista_recetas/", ListaReceta.as_view(), name="lista_recetas"),
    path("lista_semanas/", ListaSemana.as_view(), name="lista_semanas"),
    path("ingrediente/create", CrearIngrediente.as_view(), name="crear_ingrediente"),
    path("ingrediente/delete/<int:pk>", BorrarIngrediente.as_view(), name="borrar_ingrediente"),
    path("ingrediente/edit/<int:pk>", ActualizarIngrediente.as_view(), name="actualizar_ingrediente"),
    path("ingrediente/<int:pk>", DetalleIngrediente.as_view(), name="detalle_ingrediente"),
    path("semana/create", CrearSemana2.as_view(), name="crear_semana"),
    path("semana/<int:pk>", DetalleSemana.as_view(), name="detalle_semana"),
    path("semana/edit/<int:pk>", ActualizarSemana.as_view(), name="actualizar_semana"),
    path("semana/delete/<int:pk>", BorrarSemana.as_view(), name="borrar_semana"),
    path("receta/create", CrearReceta.as_view(), name="crear_receta"),
    path("receta/<int:pk>", DetalleReceta.as_view(), name="detalle_receta"),
    path("receta/delete/<int:pk>", BorrarReceta.as_view(), name="borrar_receta"),
    path("receta/edit/<int:pk>", ActualizarReceta.as_view(), name="actualizar_receta"),
    # path('', index, name='index'),
]

recetas_compras/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Ingrediente(models.Model):
    TYPE_UNIDAD = [
        ("PEN", "Soles"),
        ("KG", "Kilos"),
        ("LT", "Litros"),
        ("GR", "Gramos"),
        ("DOC", "Docena(s)"),
        ("UN", "Unidad(es)"),
    ]

    TYPE_INGREDIENTE = [
        ("CRN", "Carnes"),
        ("VRD", "Verduras"),
        ("ESP", "Especias"),
        ("LAC", "Lacteos"),
        ("OVO", "Huevos"),
        ('FRU', 'Frutas'),
        ('GRA','Granos,Cereales'),
        ("OTR", "Otros"),
    ]
    nombre = models.CharField(max_length=100)
    tipo_ingrediente = models.CharField(
        max_length= 3,
        choices= TYPE_INGREDIENTE,
        default= 'OTR'
    )
    tipo_unidad = models.CharField(
        max_length= 3,
        choices= TYPE_UNIDAD,
        default='UN'
    )
    fecha_creacion = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.nombre

    class Meta:
        pass

    def get_absolute_url(self):
        return reverse("detalle_ingrediente", args=[str(self.id)])


class Receta(models.Model):
    TYPE_INGREDIENTE_PRINCIPAL = [
        ("AVE", "Aves"),
        ("RES", "Res"),
        ("CER", "Cerdo"),
        ("MAR", "Marino"),
        ("OVO", "Huevos"),
        ('CON', 'Conservas'),
        ("OTR", "Otros"),
    ]
    nombre = models.CharField(max_length=100)
    ingr_principal = models.CharField(
        max_length= 3,
        choices= TYPE_INGREDIENTE_PRINCIPAL,
    )
    ingredientes = models.ManyToManyField(Ingrediente, related_name= 'get_ingredientes',  through='M2MRecetario')
    image = models.ImageField(blank= True, upload_to="recetas_compras/photos", default= "recetas_compras/photos/Image_not_available.png")
    preparacion = models.TextField()
    fecha_creacion = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.nombre

    class Meta:
        pass
    
    def get_absolute_url(self):
        return reverse("detalle_receta", args=[str(self.id)])

class M2MRecetario(models.Model):
    ingrediente = models.ForeignKey(Ingrediente, on_delete= models.PROTECT)
    receta = models.ForeignKey(Receta, on_delete= models.CASCADE)
    cantidad = models.DecimalField(max_digits=3, decimal_places=1, )

    def __str__(self):
        return f'{self.receta} - {self.ingrediente}'

    class Meta:
        unique_together = [['ingrediente', 'receta']]


class Semana(models.Model):
    nombre = models.CharField(max_length=100)
    recetas = models.ManyToManyField(Receta, related_name= 'get_recetas')
    fecha_creacion = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.nombre

    class Meta:
        pass

    def get_absolute_url(self):
        return reverse("detalle_semana", args=[str(self.id)])

recetas_compras/forms.py
from django import forms
from django.forms import Select, ModelForm, inlineformset_factory, modelformset_factory
from .models import M2MRecetario, Receta, Semana


class AgregarRecetaForm(ModelForm):

    class Meta:
        model = Receta
        exclude = ()

class AgregarIngredienteForm(ModelForm):

    class Meta:
        model = M2MRecetario
        exclude = ()


M2mrecetarioFormSet = inlineformset_factory(
    Receta, M2MRecetario, form= AgregarIngredienteForm,
    fields= ['ingrediente', 'cantidad'], extra= 6, can_delete= False
)


M2mrecetarioEditFormSet = inlineformset_factory(
    Receta, M2MRecetario, form= AgregarIngredienteForm,
    fields= ['ingrediente', 'cantidad'], extra= 6, can_delete= True
)


class AgregarRecetaForm(ModelForm):

    nombre = forms.ModelChoiceField(queryset=Receta.objects.all())

SemanaRecetasFormSet = modelformset_factory(
    Receta, fields= ['nombre',], form= AgregarRecetaForm, extra= 7, can_delete= False
)


M2mSemanaFormset = inlineformset_factory(
    Receta, Semana.recetas.through, fields= ['receta', 'semana']
)


class AgregarRecetaForm2(ModelForm):

    class Meta:
        model = Semana.recetas.through
        exclude = ()


M2mSemanaFormSet2 = inlineformset_factory(
    Semana, Semana.recetas.through, form= AgregarRecetaForm2,
    fields= ['receta', ], extra= 6, can_delete= True
)

recetas_compras/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.http import HttpResponse

# Create your views here.

# def index(request):
#     return HttpResponse('Hola Mundo')

class Home(TemplateView):
    template_name = "home.html"

recetas_compras/views/views_ingredientes.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from ..models import Ingrediente


class ListaIngrediente(ListView):
    model = Ingrediente
    ordering = "nombre"
    paginate_by = 100
    template_name = "lista_ingredientes.html"
    

class CrearIngrediente(CreateView):
    model = Ingrediente
    template_name = 'ingrediente_form.html'
    fields = ['nombre', 'tipo_ingrediente', 'tipo_unidad']


class DetalleIngrediente(DetailView):
    model = Ingrediente
    template_name = 'detalle_ingrediente.html'


class BorrarIngrediente(DeleteView):
    model = Ingrediente
    success_url = reverse_lazy("lista_ingredientes")
    template_name = "confirm_delete.html"

class ActualizarIngrediente(UpdateView):
    model = Ingrediente
    template_name = 'ingrediente_form.html'
    fields = ['nombre', 'tipo_ingrediente', 'tipo_unidad']

recetas_compras/views/views_recetas.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.db import transaction
from ..forms import *
from ..models import Receta, Ingrediente

class ListaReceta(ListView):
    model = Receta
    ordering = "nombre"
    paginate_by = 100
    template_name = "lista_recetas.html"


class CrearReceta(CreateView):
    model = Receta
    fields = ['nombre', 'image', 'ingr_principal', 'preparacion']
    template_name = 'receta2_form.html'
    success_url = reverse_lazy('lista_recetas')

    def get_context_data(self, **kwargs):
        data = super(CrearReceta, self).get_context_data(**kwargs)
        if self.request.POST:
            data['ingredientes'] = M2mrecetarioFormSet(self.request.POST)
        else:
            data['ingredientes'] = M2mrecetarioFormSet()

        return data
    
    def form_valid(self, form):
        context = self.get_context_data()
        print(context)
        ingredientes = context['ingredientes']
        with transaction.atomic():
            self.object = form.save()

            if ingredientes.is_valid():
                print('valido')
                ingredientes.instance = self.object
                ingredientes.save()
        return super(CrearReceta, self).form_valid(form)


class ActualizarReceta(UpdateView):
    model = Receta
    fields = ['nombre', 'image', 'ingr_principal', 'preparacion']
    template_name = 'receta2_form.html'
    success_url = reverse_lazy('lista_recetas')

    def get_context_data(self, **kwargs):
        data = super(ActualizarReceta, self).get_context_data(**kwargs)
        if self.request.POST:
            data['ingredientes'] = M2mrecetarioEditFormSet(self.request.POST, instance= self.object)
        else:
            data['ingredientes'] = M2mrecetarioEditFormSet(instance= self.object)

        return data
    
    def form_valid(self, form):
        context = self.get_context_data()
        print(context)
        ingredientes = context['ingredientes']
        with transaction.atomic():
            self.object = form.save()

            if ingredientes.is_valid():
                print('valido')
                ingredientes.instance = self.object
                ingredientes.save()
        return super(ActualizarReceta, self).form_valid(form)


class DetalleReceta(DetailView):
    model = Receta
    template_name = 'detalle_receta.html'

    # funcion para obtener las cantidades y unidades que estan en la tabla intermedia
    def get_context_data(self, **kwargs):
        context = super(DetalleReceta, self).get_context_data(**kwargs)
        lista_ingredientes = []
        m2m_lista = self.object.m2mrecetario_set.all()

        for m2m_ingrediente in self.object.m2mrecetario_set.all():
            dict_ingr = {}
            dict_ingr['cantidad'] = m2m_ingrediente.cantidad
            ingrediente_id = m2m_ingrediente.ingrediente_id
            dict_ingr['unidad'] = Ingrediente.objects.get(id= ingrediente_id).get_tipo_unidad_display()
            dict_ingr['nombre'] = Ingrediente.objects.get(id= ingrediente_id).nombre
            lista_ingredientes.append(dict_ingr)

        if lista_ingredientes:
            context["lista_ingre"] = lista_ingredientes

        return context
    

class BorrarReceta(DeleteView):
    model = Receta
    success_url = reverse_lazy("lista_recetas")
    template_name = "confirm_delete.html"

recetas_compras/views/views_semana.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.db import transaction
from django.views.generic.base import TemplateView
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from ..forms import *
from ..models import Semana
from django.http import HttpResponse

# Create your views here.


class Home(TemplateView):
    template_name = "home.html"


class ListaSemana(ListView):
    model = Semana
    ordering = "fecha_creacion"
    paginate_by = 100
    template_name = "lista_semanas.html"


class CrearSemana(CreateView):
    model = Semana
    fields = ['nombre', 'recetas']
    template_name = 'semana_form.html'
    success_url = reverse_lazy('lista_semanas')

class ActualizarSemana(UpdateView):
    model = Semana
    fields = ['nombre', 'recetas']
    template_name = 'semana_form.html'
    success_url = reverse_lazy('lista_semanas')
  

class DetalleSemana(DetailView):
    model = Semana
    template_name = 'detalle_semana.html'


class BorrarSemana(DeleteView):
    model = Semana
    success_url = reverse_lazy("lista_semanas")
    template_name = "confirm_delete.html"


class CrearSemana2(CreateView):
    model = Semana
    fields = ['nombre', ]
    template_name = 'semana_form_old.html'
    success_url = reverse_lazy('lista_semanas')

    def get_context_data(self, **kwargs):
        data = super(CrearSemana2, self).get_context_data(**kwargs)
        if self.request.POST:
            data['recetas'] = M2mSemanaFormSet2(self.request.POST)
        else:
            data['recetas'] = M2mSemanaFormSet2()

        return data
    
    def form_valid(self, form):
        context = self.get_context_data()
        print(context)
        recetas = context['recetas']
        with transaction.atomic():
            self.object = form.save()

            if recetas.is_valid():
                print('valido')
                recetas.instance = self.object
                recetas.save()
        return super(CrearSemana2, self).form_valid(form)

recetas_compras/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Control De Compras</title>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'recetas_compras/css/styles.css' %}" rel="stylesheet"/>
</head>
<body id="page-top">
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <div class="container px-4">
        <a class="navbar-brand" href="/">Control de Compras Semanales</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
    </div>
</nav>
<!-- Header-->
<header class="bg-primary bg-gradient text-white">
    <div class="container px-4 text-center">
        <h1 class="fw-bolder">Compras domesticas App</h1>
        
    </div>
</header>

{% block content %}
{% endblock %}



<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container px-4"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

recetas_compras/templates/confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<section class="bg-light" id="director">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <form method="POST">
                    {% csrf_token %}
                    <p class="lead">Esta seguro de eliminar este registro?</p>
                    <br>
                    <button type="submit" value="Confirm" class="save btn btn-dark">confirmar</button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

recetas_compras/templates/detalle_ingrediente.html
{% extends 'base.html' %}


{% block content %}

<!-- Ingrediente section-->
<section class="bg-light" id="director">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h1>{{ object.full_name }}</h1><br>
                <h3 class="bg-light"><a href="{% url 'actualizar_ingrediente' ingrediente.id %}">Actualizar</a></h3>
                <h3 class="bg-light"><a href="{% url 'borrar_ingrediente' ingrediente.id %}">Eliminar</a></h3>
                <br><br>
                {% if user.is_authenticated %}
                    <h3 class="bg-light"><a href="/">Actualizar</a></h3>
                    <h3 class="bg-light"><a href="{% url 'borrar_ingrediente' ingrediente.id %}">Eliminar</a></h3>
                    <br><br>
                {% endif %}
            </div>
            <div class="col-lg-8">
                <h2>Ingrediente</h2>
                <p class="lead">{{ object.nombre }}</p>
                <br>

                <h3>Tipo de Ingrediente</h3>
                <p class="lead">{{ object.get_tipo_ingrediente_display }}</p><br>

                <h3>Tipo de Unidad</h3>
                <p class="lead">{{ object.get_tipo_unidad_display }}</p><br>
            </div>
        </div>
    </div>
</section>

{% endblock %}

recetas_compras/templates/detalle_receta.html
{% extends 'base.html' %}

{% block content %}

<!-- Ingrediente section-->
<section class="bg-light" id="director">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h1>{{ object.full_name }}</h1><br>
                <h3 class="bg-light"><a href="{% url 'actualizar_receta' receta.id %}">Actualizar</a></h3>
                <h3 class="bg-light"><a href="{% url 'borrar_receta' receta.id %}">Eliminar</a></h3>
                {% if user.is_authenticated %}
                    <h3 class="bg-light"><a href="/">Actualizar</a></h3>
                    <h3 class="bg-light"><a href="/">Eliminar</a></h3>
                    <br><br>
                {% endif %}
            </div>
            <div class="col-5">
                <img src={{ object.image.url }} class="img-fluid">
                
            </div>
            <div class="col-lg-8">
                <h2>Receta</h2>
                <p class="lead">{{ object.nombre }}</p>
                <br>


                <h3>Principal:</h3>
                <p class="lead">{{ object.get_ingr_principal_display }}</p>
                <br>

                <h3>Ingredientes:</h3>
                
                {% for ingr_receta in lista_ingre %}
                <ul>
                     <li><span style="width:55px; display: inline-block;">{{ ingr_receta.cantidad }}</span>
                        <span style="width:100px; display: inline-block;">{{ ingr_receta.unidad }}</span>
                        <span>{{ ingr_receta.nombre }}</span></a></li>
                </ul>
            {% endfor %}
            <h2>Preparacion:</h2>
            <p class="lead">{{ object.preparacion }}</p>
            </div>
        </div>
    </div>
</section>

{% endblock %}

recetas_compras/templates/detalle_semana.html
{% extends 'base.html' %}


{% block content %}

<!-- Ingrediente section-->
<section class="bg-light" id="director">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h1>{{ object.full_name }}</h1><br>
                <h3 class="bg-light"><a href="{% url 'actualizar_semana' semana.id %}">Actualizar</a></h3>
                <h3 class="bg-light"><a href="{% url 'borrar_semana' semana.id %}">Eliminar</a></h3>
                {% if user.is_authenticated %}
                    <h3 class="bg-light"><a href="/">Actualizar</a></h3>
                    <h3 class="bg-light"><a href="/">Eliminar</a></h3>
                    <br><br>
                {% endif %}
            </div>
            <div class="col-lg-8">
                <h2>Compras Semanales</h2>
                <p class="lead">{{ object.nombre }}</p>
                <br>

                <h3>Recetas</h3>
                <p class="lead">
                    {% for receta in object.recetas.all %}
                    <ul>
                 
                        <li><a href="{{ receta.get_absolute_url }}">{{ receta }}</a></li>
                    </ul>
                        
                    {% endfor %}
                </p><br>

            </div>
        </div>
    </div>
</section>

{% endblock %}

recetas_compras/templates/home.html
{% extends 'base.html' %}
{% block content %}

<section id="home" class="py-5">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h2>Informacion</h2>
                    <p class="lead"><a href="{% url 'lista_semanas' %}">Listado de Compras Semanas</a></p>
                    <p class="lead"><a href="{% url 'lista_recetas' %}">Listado de Recetas</a></p>
                    <p class="lead"><a href="{% url 'lista_ingredientes' %}">Listado de Ingredientes</a></p>
            </div>
        </div>
    </div>
</section>

{% endblock %}

recetas_compras/templates/ingre_form.html
{% extends 'base.html' %}
{% block content %}

<section class="bg-light" id="director">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h1>Crear/Actualizar Ingrediente</h1><br><br>
            </div>
            <div class="col-lg-8">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table class="table-light" >
                        {{ form.as_table }}
                    </table>
                    <br>
                    <button type="submit" class="save btn btn-dark">Save</button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

recetas_compras/templates/ingrediente_form.html
{% extends 'base.html' %}
{% block content %}

<section class="bg-light" id="director">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h1>Crear/Actualizar Ingrediente</h1><br><br>
            </div>
            <div class="col-lg-8">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table class="table-light" >
                        {{ form.as_table }}
                    </table>
                    <br>
                    <button type="submit" class="save btn btn-dark">Save</button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

recetas_compras/templates/lista_ingredientes.html
{% extends 'base.html' %}
{% block content %}

<section id="home" class="py-5">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h2>Listado de Ingredientes</h2>
                <br>
                {% if user.is_authenticated %}
                    <h3 class="bg-light"><a href="/">Añadir Ingrediente</a></h3>
                {% endif %}
                <br><br>
                <table class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Tipo Ingrediente</th>
                        <th scope="col">Unidad de medida</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for ingrediente in object_list %}
                    <tr>
                        <th scope="row">{{ ingrediente.id }}</th>
                        <td><!-- a href="{{ actor.get_absolute_url }}"-->{{ ingrediente }}</td>
                        <td>{{ ingrediente.tipo_ingrediente }}</td>
                        <td>{{ ingrediente.<td>{{ ingrediente.tipo_ingrediente }}</td> }}</td>
                    </tr>
                    {% empty %}
                        <p>No hay ingredientes disponibles.</p>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

{% endblock %}

recetas_compras/templates/lista_recetas.html
{% extends 'base.html' %}
{% block content %}

<section id="home" class="py-5">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h2>Listado de Recetas</h2>
                <h3 class="bg-light"><a href="{% url 'crear_receta' %}">Añadir Receta</a></h3>
                <br>
                {% if user.is_authenticated %}
                    <h3 class="bg-light"><a href="/">Añadir Receta</a></h3>
                {% endif %}
                <br><br>
                <table class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Principal</th>
                        
                    </tr>
                    </thead>
                    <tbody>
                    {% for receta in object_list %}
                    <tr>
                        <th scope="row">{{ receta.id }}</th>
                        <td><a href="{{ receta.get_absolute_url }}">{{ receta }}</td>
                        <td>{{ receta.get_ingr_principal_display }}</td>

                    </tr>
                    {% empty %}
                        <p>No hay recetas disponibles.</p>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

{% endblock %}

recetas_compras/templates/receta2_form.html
{% extends 'base.html' %}
{% block content %}

<section class="bg-light" id="director">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h1>Crear/Actualizar Receta</h1><br><br>
            </div>
            <div class="col-lg-8">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table class="table-light" >
                        {{ form.as_table }}
                    </table>
                    <table class="table-light" >

                            {{ ingredientes.management_form }}
                            {% for form in ingredientes %}
                            {{ form.id }}
                                {% for field in form.visible_fields %}
                                    {{ field.label_tag }} {{ field }}
                                {% endfor %}
                                <p></p>
                            {% endfor %}

                    </table>
                    <br>
                    <button type="submit" class="save btn btn-dark">Save</button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

recetas_compras/templates/receta_form.html
{% extends 'base.html' %}
{% block content %}

<section class="bg-light" id="director">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h1>Crear/Actualizar Receta</h1><br><br>
            </div>
            <div class="col-lg-8">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table class="table-light" >
                        {{ form.as_table }}
                    </table>
                    <br>
                    <button type="submit" class="save btn btn-dark">Save</button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

recetas_compras/templates/semana_form.html
{% extends 'base.html' %}
{% block content %}

<section class="bg-light" id="director">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h1>Crear/Actualizar Semana</h1><br><br>
            </div>
            <div class="col-lg-8">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table class="table-light" >
                        {{ form.as_table }}
                    </table>
                    <table class="table-light" >

                            {{ recetas.management_form }}
                            {% for form in recetas %}
                            {{ form.id }}
                                {% for field in form.visible_fields %}
                                    {{ field.label_tag }} {{ field }}
                                {% endfor %}
                                <p></p>
                            {% endfor %}

                    </table>
                    <br>
                    <button type="submit" class="save btn btn-dark">Save</button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

recetas_compras/templates/semana_form_old.html
{% extends 'base.html' %}
{% block content %}

<section class="bg-light" id="director">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h1>Crear/Actualizar Semana</h1><br><br>
            </div>
            <div class="col-lg-8">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table class="table-light" >
                        {{ form.as_table }}
                    </table>
                    <table class="table-light" >

                            {{ recetas.management_form }}
                            {% for form in recetas %}
                            {{ form.id }}
                                {% for field in form.visible_fields %}
                                    {{ field.label_tag }} {{ field }}
                                {% endfor %}
                                <p></p>
                            {% endfor %}

                    </table>
                    <br>
                    <button type="submit" class="save btn btn-dark">Save</button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}